SCHEMES = [
    {
        "scheme_id": "micro_finance",
        "name": "Micro Finance",
        "purpose": "business",
        "min_project_amount": 1,
        "max_project_amount": 140000,
        "maximum_loan_amount": 125000,
        "max_income": 300000,
        "allowed_categories": ["SC", "ST", "OBC"],
        "certificate_required": True,
        "interest_rate": 6.5,
        "repayment_years": 3,
        "moratorium_months": 3,
    },
    {
        "scheme_id": "term_loan",
        "name": "Term Loan",
        "purpose": "business",
        "min_project_amount": 140001,
        "max_project_amount": 5000000,
        "maximum_loan_amount": 4500000,
        "max_income": 800000,
        "allowed_categories": ["SC", "ST", "OBC"],
        "certificate_required": True,
        "interest_rate": 8.0,
        "repayment_years": 7,
        "moratorium_months": 6,
    },
    {
        "scheme_id": "education_loan",
        "name": "Educational Loan",
        "purpose": "education",
        "min_project_amount": 1,
        "max_project_amount": 5000000,
        "maximum_loan_amount": 4000000,
        "max_income": 800000,
        "allowed_categories": ["SC", "ST", "OBC"],
        "certificate_required": True,
        "interest_rate": 6.5,
        "repayment_years": 10,
        "moratorium_months": 18,
    },
]
